### ISSUE TITLE
Im getting this error in a new instalation

### ISSUE THREAD

**Issue by fulvio-diller** [shopware/dev-tools#4]
```
{
  "license": "proprietary",
  "type": "project",
  "require":
  {
    "composer-runtime-api": "^2.0",
    "shopware/administration": "*",
    "shopware/core": "v6.6.2.0",
    "shopware/elasticsearch": "*",
    "shopware/storefront": "*",
    "symfony/flex": "~2"
  },
  "repositories":
  [
    {
      "type": "path",
      "url": "custom/plugins/*",
      "options":
      {
        "symlink": true
      }
    },
    {
      "type": "path",
      "url": "custom/plugins/*/packages/*",
      "options":
      {
        "symlink": true
      }
    },
    {
      "type": "path",
      "url": "custom/static-plugins/*",
      "options":
      {
        "symlink": true
      }
    }
  ],
  "minimum-stability": "stable",
  "prefer-stable": true,
  "config":
  {
    "allow-plugins":
    {
      "symfony/flex": true,
      "symfony/runtime": true
    },
    "optimize-autoloader": true,
    "sort-packages": true
  },
  "scripts":
  {
    "auto-scripts": {
      "assets:install": "symfony-cmd"
    },
    "post-install-cmd":
    [
      "@auto-scripts"
    ],
    "post-update-cmd":
    [
      "@auto-scripts"
    ]
  },
  "extra":
  {
    "symfony":
    {
      "allow-contrib": true,
      "endpoint":
      [
        "https://raw.githubusercontent.com/shopware/recipes/flex/main/index.json",
        "flex://defaults"
      ]
    }
  }
}
```

In PluginManager.php line 752:
                                                                               
  symfony/runtime contains a Composer plugin which is blocked by your allow-p  
  lugins config. You may add it to the list if you consider it safe.           
  You can run "composer config --no-plugins allow-plugins.symfony/runtime [tr  
  ue|false]" to enable it (true) or disable it explicitly and suppress this e  
  xception (false)                                                             
  See https://getcomposer.org/allow-plugins                                    
                                                                               

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-m|--minimal-changes] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]

**Comment by shyim** [comment]
You have to run once `composer config --no-plugins allow-plugins.symfony/runtime` as the error says
